# Generated by Django 2.2.6 on 2019-10-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Sold', 'Item already purchased'), ('Sold Out', 'Item comming soon'), ('Available', 'Item ready to purchase')], default='Sold', max_length=30)),
                ('remarks', models.CharField(default='No Issues', max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Device')),
            ],
            bases=('products.device',),
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Device')),
            ],
            bases=('products.device',),
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Device')),
            ],
            bases=('products.device',),
        ),
    ]
